# Generated by Django 5.2.5 on 2026-08-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('host_name', models.CharField(db_index=True, max_length=200)),
                ('is_solar_system', models.BooleanField(default=False)),
                ('discovery_year', models.IntegerField(blank=True, null=True)),
                ('discovery_method', models.CharField(blank=True, max_length=100, null=True)),
                ('star_spectral_type', models.CharField(blank=True, max_length=20, null=True)),
                ('star_teff_k', models.FloatField(blank=True, null=True)),
                ('star_color_rgb', models.JSONField(blank=True, null=True)),
                ('star_radius_solar', models.FloatField(blank=True, null=True)),
                ('star_mass_solar', models.FloatField(blank=True, null=True)),
                ('star_age_gyr', models.FloatField(blank=True, null=True)),
                ('star_luminosity_solar', models.FloatField(blank=True, null=True)),
                ('orbit_semi_major_axis_au', models.FloatField(blank=True, null=True)),
                ('orbit_eccentricity', models.FloatField(blank=True, null=True)),
                ('orbit_inclination_deg', models.FloatField(blank=True, null=True)),
                ('orbit_period_days', models.FloatField(blank=True, null=True)),
                ('rotation_state', models.CharField(blank=True, max_length=20, null=True)),
                ('system_planet_count', models.IntegerField(blank=True, null=True)),
                ('system_position', models.IntegerField(blank=True, null=True)),
                ('planet_type', models.CharField(blank=True, max_length=30, null=True)),
                ('planet_color_rgb', models.JSONField(blank=True, null=True)),
                ('moon_count', models.IntegerField(blank=True, null=True)),
                ('has_rings', models.BooleanField(blank=True, null=True)),
                ('visual_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('mass_earth', models.FloatField(blank=True, null=True)),
                ('radius_earth', models.FloatField(blank=True, null=True)),
                ('density_g_cm3', models.FloatField(blank=True, null=True)),
                ('surface_gravity_g', models.FloatField(blank=True, null=True)),
                ('escape_velocity_km_s', models.FloatField(blank=True, null=True)),
                ('equilibrium_temp_k', models.FloatField(blank=True, null=True)),
                ('insolation_flux_earth', models.FloatField(blank=True, null=True)),
                ('distance_from_earth_ly', models.FloatField(blank=True, null=True)),
                ('hz_inner_au', models.FloatField(blank=True, null=True)),
                ('hz_outer_au', models.FloatField(blank=True, null=True)),
                ('in_habitable_zone', models.BooleanField(blank=True, null=True)),
                ('atmosphere_density', models.CharField(blank=True, max_length=20, null=True)),
                ('detected_molecules', models.JSONField(blank=True, null=True)),
                ('molecule_source', models.CharField(blank=True, max_length=30, null=True)),
                ('c_to_o_ratio', models.FloatField(blank=True, null=True)),
                ('magnetosphere_strength', models.CharField(blank=True, max_length=20, null=True)),
                ('tectonic_activity', models.CharField(blank=True, max_length=20, null=True)),
                ('esi_score', models.FloatField(blank=True, null=True)),
                ('habitability_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('resource_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('biosignature_candidate', models.BooleanField(blank=True, null=True)),
                ('market_value_credits', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-habitability_score'],
            },
        ),
    ]
