# Generated by Django 5.2.5 on 2026-08-07 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('space_mission', 'Ruimtemissie (bv. lancering, nieuwe observatiecampagne)'), ('tech_breakthrough', 'Technologische doorbraak (bv. voortstuwing, detectiemethode)'), ('market_sentiment', 'Algemeen marktsentiment (bv. stabiliteitsindex) -- GEEN directe verwijzing naar echte conflicten/tragedies in titel of beschrijving'), ('discovery', 'Wetenschappelijke ontdekking (bv. nieuw biosignature-onderzoek)')], max_length=30)),
                ('scope', models.CharField(choices=[('global', 'Alle planeten'), ('system', 'Specifiek sterrenstelsel (host_name)'), ('planet_type', 'Specifiek planeettype'), ('planet', 'Specifieke planeet')], default='global', max_length=20)),
                ('scope_value', models.CharField(blank=True, help_text="Alleen invullen bij scope != 'global': host_name, planet_type, of planet_name.", max_length=200, null=True)),
                ('magnitude', models.FloatField(help_text='Bv. 0.15 voor +15%, -0.10 voor -10%.')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('half_life_days', models.FloatField(default=14, help_text='Na hoeveel dagen het effect gehalveerd is.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_auto_generated', models.BooleanField(default=False, help_text='True voor door sync_market_sentiment gegenereerde events -- deze worden bij elke run vervangen, niet handmatig bewerken.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('host_name', models.CharField(db_index=True, max_length=200)),
                ('is_solar_system', models.BooleanField(default=False)),
                ('discovery_year', models.IntegerField(blank=True, null=True)),
                ('discovery_method', models.CharField(blank=True, max_length=100, null=True)),
                ('star_spectral_type', models.CharField(blank=True, max_length=20, null=True)),
                ('star_teff_k', models.FloatField(blank=True, null=True)),
                ('star_color_rgb', models.JSONField(blank=True, null=True)),
                ('star_radius_solar', models.FloatField(blank=True, null=True)),
                ('star_mass_solar', models.FloatField(blank=True, null=True)),
                ('star_age_gyr', models.FloatField(blank=True, null=True)),
                ('star_luminosity_solar', models.FloatField(blank=True, null=True)),
                ('orbit_semi_major_axis_au', models.FloatField(blank=True, null=True)),
                ('orbit_eccentricity', models.FloatField(blank=True, null=True)),
                ('orbit_inclination_deg', models.FloatField(blank=True, null=True)),
                ('orbit_period_days', models.FloatField(blank=True, null=True)),
                ('rotation_state', models.CharField(blank=True, max_length=20, null=True)),
                ('system_planet_count', models.IntegerField(blank=True, null=True)),
                ('system_position', models.IntegerField(blank=True, null=True)),
                ('planet_type', models.CharField(blank=True, max_length=30, null=True)),
                ('planet_color_rgb', models.JSONField(blank=True, null=True)),
                ('moon_count', models.IntegerField(blank=True, null=True)),
                ('has_rings', models.BooleanField(blank=True, null=True)),
                ('visual_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('mass_earth', models.FloatField(blank=True, null=True)),
                ('radius_earth', models.FloatField(blank=True, null=True)),
                ('density_g_cm3', models.FloatField(blank=True, null=True)),
                ('surface_gravity_g', models.FloatField(blank=True, null=True)),
                ('escape_velocity_km_s', models.FloatField(blank=True, null=True)),
                ('equilibrium_temp_k', models.FloatField(blank=True, null=True)),
                ('insolation_flux_earth', models.FloatField(blank=True, null=True)),
                ('distance_from_earth_ly', models.FloatField(blank=True, null=True)),
                ('hz_inner_au', models.FloatField(blank=True, null=True)),
                ('hz_outer_au', models.FloatField(blank=True, null=True)),
                ('in_habitable_zone', models.BooleanField(blank=True, null=True)),
                ('atmosphere_density', models.CharField(blank=True, max_length=20, null=True)),
                ('detected_molecules', models.JSONField(blank=True, null=True)),
                ('molecule_source', models.CharField(blank=True, max_length=30, null=True)),
                ('c_to_o_ratio', models.FloatField(blank=True, null=True)),
                ('magnetosphere_strength', models.CharField(blank=True, max_length=20, null=True)),
                ('tectonic_activity', models.CharField(blank=True, max_length=20, null=True)),
                ('esi_score', models.FloatField(blank=True, null=True)),
                ('habitability_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('base_resource_score', models.FloatField(blank=True, null=True)),
                ('resource_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('biosignature_candidate', models.BooleanField(blank=True, null=True)),
                ('base_market_value_credits', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('market_sentiment_multiplier', models.FloatField(default=1.0)),
                ('demand_multiplier', models.FloatField(default=1.0, help_text='Vraag/populariteit op ons EIGEN platform (koop/verkoop-activiteit), los van externe marktsentiment.')),
                ('market_value_credits', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-habitability_score'],
            },
        ),
        migrations.CreateModel(
            name='ResourceDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Bronvermelding/publicatie.', max_length=300)),
                ('points_bonus', models.FloatField(help_text='Punten opgeteld bij base_resource_score (kan ook negatief zijn bij weerlegging).')),
                ('is_verified', models.BooleanField(default=True, help_text='Alleen geverifieerde ontdekkingen tellen mee -- zet uit om tijdelijk te pauzeren zonder te verwijderen.')),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_discoveries', to='catalog.planet')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
    ]
